spring:
  main:
    banner-mode: off
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate

  application:
    name: DistanceOnEarth
  datasource:
    url: jdbc:mysql://mysql:3306/distance?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-init-sql: SET TIME_ZONE='+00:00'
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

yandex:
  api:
    key: ${YANDEX_API_KEY}
dadata:
  api:
    key: ${DADATA_API_KEY}
    secret: ${DADATA_API_SECRET}

